{% set name = "parsita" %}
{% set version = "2.3.0" %}
{% set python_version = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/parsita-{{ version }}.tar.gz
  sha256: 7f8b3af94e8ae4e7ca77e9ba8621d813a23f2e9cdd3ffdc5c767070eb050f062

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_version }}
    - uv-build >=0.8,<0.9
    - pip
  run:
    - python >={{ python_version }}
    - returns >=0.20.0,<0.27

test:
  requires:
    - python {{ python_version }}
    - pip
  imports:
    - parsita
  commands:
    - pip check

about:
  home: https://parsita.drhagen.com/
  summary: Parser combinator library for Python
  license: MIT
  license_file: LICENSE
  doc_url: https://parsita.drhagen.com/
  dev_url: https://github.com/drhagen/parsita/

extra:
  recipe-maintainers:
    - drhagen
