{% set name = "parsita" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/parsita-{{ version }}.tar.gz
  sha256: 054f6a20a82b890ed3c9201e773c7c53565db443b922804d7d6e8f8ca03c4fdd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - returns >=0.20.0,<0.24

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - parsita
  commands:
    - pip check

about:
  home: https://parsita.drhagen.com/
  summary: Parser combinator library for Python
  license: MIT
  license_file: LICENSE
  doc_url: https://parsita.drhagen.com/
  dev_url: https://github.com/drhagen/parsita/

extra:
  recipe-maintainers:
    - drhagen
