{% set name = "parsita" %}
{% set version = "2.2.3" %}
{% set python_version = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/parsita-{{ version }}.tar.gz
  sha256: d0a009c0efab78b56445c4236874277930d723b0b06599e9019eee1ab3de4b7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_version }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_version }}
    - returns >=0.20.0,<0.27

test:
  requires:
    - python {{ python_version }}
    - pip
  imports:
    - parsita
  commands:
    - pip check

about:
  home: https://parsita.drhagen.com/
  summary: Parser combinator library for Python
  license: MIT
  license_file: LICENSE
  doc_url: https://parsita.drhagen.com/
  dev_url: https://github.com/drhagen/parsita/

extra:
  recipe-maintainers:
    - drhagen
