{% set name = "parsita" %}
{% set version = "2.2.2" %}
{% set python_version = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/parsita-{{ version }}.tar.gz
  sha256: 665e669e2277abccf83dba07603254d40668df039ebe8501f5729f1a32fc7fce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_version }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_version }}
    - returns >=0.20.0,<0.24

test:
  requires:
    - python {{ python_version }}
    - pip
  imports:
    - parsita
  commands:
    - pip check

about:
  home: https://parsita.drhagen.com/
  summary: Parser combinator library for Python
  license: MIT
  license_file: LICENSE
  doc_url: https://parsita.drhagen.com/
  dev_url: https://github.com/drhagen/parsita/

extra:
  recipe-maintainers:
    - drhagen
