{% set name = "parsita" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/parsita-{{ version }}.tar.gz
  sha256: 30e149d3b17113de63f0e049c36ca56e3002d57c89668c19adb6a0d16dbaab9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7
    - returns >=0.19.0,<0.20
    - deprecated >=1.2,<2

test:
  requires:
    - pip
  imports:
    - parsita
  commands:
    - pip check

about:
  home: https://parsita.drhagen.com/
  summary: Parser combinator library for Python
  license: MIT
  license_file: LICENSE
  doc_url: https://parsita.drhagen.com/
  dev_url: https://github.com/drhagen/parsita/

extra:
  recipe-maintainers:
    - drhagen
